# Clippy configuration
# Following Rust Coding Guidelines: https://rust-lang.github.io/rust-clippy/master/index.html

# Documentation
missing-docs-in-crate-items = true

# Cognitive complexity
cognitive-complexity-threshold = 30

# Type complexity
type-complexity-threshold = 250

# Too many arguments
too-many-arguments-threshold = 7

# Too many lines
too-many-lines-threshold = 100

# Trivial bounds
trivial-bounds = true

# Single char lifetime names
single-char-lifetime-names-threshold = 4

# Avoid breaking exported API
avoid-breaking-exported-api = true

# Maximum struct field count
max-struct-field-count = 20

# Maximum function parameter count
max-fn-params-bools = 3

# Enum variant name threshold
enum-variant-name-threshold = 3

# Maximum trait bounds
max-trait-bounds = 3

# Verbose bit mask threshold
verbose-bit-mask-threshold = 1

# Allow certain lints that may be too restrictive for this project
allow-expect-in-tests = true
allow-unwrap-in-tests = true
