# Rust formatting configuration
# Following Rust Style Guide: https://rust-lang.github.io/rust-style-guide/

# Edition
edition = "2021"

# Line width
max_width = 100

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions
fn_single_line = false
where_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80

# Formatting
use_small_heuristics = "Default"
newline_style = "Unix"

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true

# Spaces
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Match
match_block_trailing_comma = false

# Misc
remove_nested_parens = true
use_field_init_shorthand = false
force_explicit_abi = true
