// Auto-generated precompiled schemas
// Generated by justfile build-precompiled-schemas command
// DO NOT EDIT MANUALLY

#[cfg(feature = "embedded-providers")]
pub mod schemas {
    /// Precompiled schemas for FHIR R4
    pub static R4_SCHEMAS: &[u8] = include_bytes!("../../precompiled_schemas/r4_schemas.bin");
    
    /// Precompiled schemas for FHIR R4B
    pub static R4B_SCHEMAS: &[u8] = include_bytes!("../../precompiled_schemas/r4b_schemas.bin");
    
    /// Precompiled schemas for FHIR R5
    pub static R5_SCHEMAS: &[u8] = include_bytes!("../../precompiled_schemas/r5_schemas.bin");
    
    /// Precompiled schemas for FHIR R6
    pub static R6_SCHEMAS: &[u8] = include_bytes!("../../precompiled_schemas/r6_schemas.bin");

    /// Get precompiled schemas for a FHIR version
    pub fn get_schemas(version: &str) -> Option<&'static [u8]> {
        match version {
            "r4" => Some(R4_SCHEMAS),
            "r4b" => Some(R4B_SCHEMAS),
            "r5" => Some(R5_SCHEMAS),
            "r6" => Some(R6_SCHEMAS),
            _ => None,
        }
    }

    /// Get all available FHIR versions with precompiled schemas
    pub fn available_versions() -> &'static [&'static str] {
        &["r4", "r4b", "r5", "r6"]
    }
}
